name: Test
on: [push, pull_request]
jobs:
    test:
        name: Test on node v${{ matrix.node-version }} (${{ matrix.os }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [18, 20]
                os: [ubuntu-latest]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                version: latest

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Linting
              run: pnpm run lint

            - name: Run TypeScript compiler
              run: pnpm run build:check

            - name: Run tests
              run: pnpm run test:coverage

            - name: Upload Coverage
              uses: codecov/codecov-action@v3
